import type { Metadata } from "next";
import Bootstrapp from "@/components/Bootstrap";
import "./globals.css";
import Navbar from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "Inicio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
		<body>
			<Navbar></Navbar>
			{children}
			<Footer></Footer>
			<Bootstrapp />
		</body>
		</html>
	);
}
